package com;

/**
* com/ClinicTasksHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicTasks.idl
* Wednesday, August 3, 2016 7:56:17 PM EDT
*/

public final class ClinicTasksHolder implements org.omg.CORBA.portable.Streamable
{
  public com.ClinicTasks value = null;

  public ClinicTasksHolder ()
  {
  }

  public ClinicTasksHolder (com.ClinicTasks initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.ClinicTasksHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.ClinicTasksHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.ClinicTasksHelper.type ();
  }

}
