package Server_Group.Replica_3.com;

/**
* com/ClinicTasksHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicTasks.idl
* Wednesday, August 3, 2016 9:09:28 PM EDT
*/

public final class ClinicTasksHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Group.Replica_3.com.ClinicTasks value = null;

  public ClinicTasksHolder ()
  {
  }

  public ClinicTasksHolder (Server_Group.Replica_3.com.ClinicTasks initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Group.Replica_3.com.ClinicTasksHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Group.Replica_3.com.ClinicTasksHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Group.Replica_3.com.ClinicTasksHelper.type ();
  }

}
