package Server_Group.Replica_3.com;


/**
* com/ClinicTasks.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicTasks.idl
* Wednesday, August 3, 2016 9:09:28 PM EDT
*/

public interface ClinicTasks extends ClinicTasksOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClinicTasks
