package com;

/**
* com/SuperRecordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicTasks.idl
* Wednesday, August 3, 2016 7:56:17 PM EDT
*/

public final class SuperRecordHolder implements org.omg.CORBA.portable.Streamable
{
  public com.SuperRecord value = null;

  public SuperRecordHolder ()
  {
  }

  public SuperRecordHolder (com.SuperRecord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.SuperRecordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.SuperRecordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.SuperRecordHelper.type ();
  }

}
