package Server_Group.Replica_3.com;


/**
* com/SuperRecordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicTasks.idl
* Wednesday, August 3, 2016 9:09:28 PM EDT
*/

public final class SuperRecordHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Group.Replica_3.com.SuperRecord value = null;

  public SuperRecordHolder ()
  {
  }

  public SuperRecordHolder (Server_Group.Replica_3.com.SuperRecord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Group.Replica_3.com.SuperRecordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Server_Group.Replica_3.com.SuperRecordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Group.Replica_3.com.SuperRecordHelper.type ();
  }

}
