package com;


/**
* com/SuperRecord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicTasks.idl
* Wednesday, August 3, 2016 7:56:17 PM EDT
*/

public final class SuperRecord implements org.omg.CORBA.portable.IDLEntity
{
  public String recordID = null;
  public String managerID = null;
  public String firstName = null;
  public String lastName = null;
  public String recType = null;

  // used to differentiate doctor and Nurse
  public int designation = (int)0;
  public int status = (int)0;
  public String statusDate = null;
  public int category = (int)0;
  public String address = null;
  public String phoneNumber = null;
  public int specialization = (int)0;
  public int location = (int)0;

  public SuperRecord ()
  {
  } // ctor

  public SuperRecord (String _recordID, String _managerID, String _firstName, String _lastName, String _recType, int _designation, int _status, String _statusDate, int _category, String _address, String _phoneNumber, int _specialization, int _location)
  {
    recordID = _recordID;
    managerID = _managerID;
    firstName = _firstName;
    lastName = _lastName;
    recType = _recType;
    designation = _designation;
    status = _status;
    statusDate = _statusDate;
    category = _category;
    address = _address;
    phoneNumber = _phoneNumber;
    specialization = _specialization;
    location = _location;
  } // ctor

} // class SuperRecord
