package Front_End.FRONT_END_CORBA;


/**
* FRONT_END_CORBA/Front_EndHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Front_End.idl
* Wednesday, July 27, 2016 7:42:35 PM EDT
*/

abstract public class Front_EndHelper
{
  private static String  _id = "IDL:FRONT_END_CORBA/Front_End:1.0";

  public static void insert (org.omg.CORBA.Any a, Front_End that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Front_End extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Front_EndHelper.id (), "Front_End");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Front_End read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Front_EndStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Front_End value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Front_End narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Front_End)
      return (Front_End)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _Front_EndStub stub = new _Front_EndStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Front_End unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Front_End)
      return (Front_End)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _Front_EndStub stub = new _Front_EndStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
