package Front_End.FRONT_END_CORBA;


/**
* FRONT_END_CORBA/Front_End.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Front_End.idl
* Wednesday, July 27, 2016 7:42:35 PM EDT
*/

public interface Front_End extends Front_EndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Front_End
