package Front_End.FRONT_END_CORBA;


/**
* FRONT_END_CORBA/Front_EndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Front_End.idl
* Wednesday, July 27, 2016 7:42:35 PM EDT
*/

public interface Front_EndOperations 
{
  String createDRecord (String managerId, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createNRecord (String managerId, String firstName, String lastName, String designation, String status, String statusDate);
  String getRecordCounts (String managerId, String recordType);
  String editRecord (String managerId, String recordID, String fieldName, String newValue);
  String transferRecord (String managerId, String recordID, String remoteClinicServerName);
} // interface Front_EndOperations
