package FRONT_END_CORBA;


/**
* FRONT_END_CORBA/Front_End.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Front_End.idl
* Thursday, July 21, 2016 5:42:26 PM EDT
*/

public interface Front_End extends Front_EndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Front_End
