package FRONT_END_CORBA;

/**
* FRONT_END_CORBA/Front_EndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Front_End.idl
* Thursday, July 21, 2016 5:42:26 PM EDT
*/

public final class Front_EndHolder implements org.omg.CORBA.portable.Streamable
{
  public FRONT_END_CORBA.Front_End value = null;

  public Front_EndHolder ()
  {
  }

  public Front_EndHolder (FRONT_END_CORBA.Front_End initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FRONT_END_CORBA.Front_EndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FRONT_END_CORBA.Front_EndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FRONT_END_CORBA.Front_EndHelper.type ();
  }

}
