package Server_Group.Replica_2.ClinicServer;


/**
* ClinicServer/ClinicServerIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServer.idl
* Sunday, July 31, 2016 1:56:33 PM EDT
*/

abstract public class ClinicServerIntHelper
{
  private static String  _id = "IDL:ClinicServer/ClinicServerInt:1.0";

  public static void insert (org.omg.CORBA.Any a, Server_Group.Replica_2.ClinicServer.ClinicServerInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Server_Group.Replica_2.ClinicServer.ClinicServerInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Server_Group.Replica_2.ClinicServer.ClinicServerIntHelper.id (), "ClinicServerInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Server_Group.Replica_2.ClinicServer.ClinicServerInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClinicServerIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Server_Group.Replica_2.ClinicServer.ClinicServerInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Server_Group.Replica_2.ClinicServer.ClinicServerInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server_Group.Replica_2.ClinicServer.ClinicServerInt)
      return (Server_Group.Replica_2.ClinicServer.ClinicServerInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server_Group.Replica_2.ClinicServer._ClinicServerIntStub stub = new Server_Group.Replica_2.ClinicServer._ClinicServerIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Server_Group.Replica_2.ClinicServer.ClinicServerInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Server_Group.Replica_2.ClinicServer.ClinicServerInt)
      return (Server_Group.Replica_2.ClinicServer.ClinicServerInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Server_Group.Replica_2.ClinicServer._ClinicServerIntStub stub = new Server_Group.Replica_2.ClinicServer._ClinicServerIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
