package Server_Group.Replica_2.ClinicServer;


/**
* ClinicServer/ClinicServerInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServer.idl
* Sunday, July 31, 2016 1:56:33 PM EDT
*/

public interface ClinicServerInt extends ClinicServerIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClinicServerInt
