module ClinicServer{
	interface ClinicServerInt{
		string createDRecord (
				in string managerId,
				in string firstName,
			  	in string lastName,
			  	in string address,
			  	in string phone,
			  	in string specialization,
			  	in string location);
			  
		string createNRecord (
				in string mangerId,
				in string firstName,
			  	in string lastName,
			  	in string designation,
			  	in string status,
			  	in string statusDate);
			  
		string getRecordCounts (
				in string managerId,
				in string recordType);
		
		string editRecord (
				in string managerId,
				in string recordID,
				in string fieldName,
				in string newValue);
		
		string transferRecord (
				in string managerID,
				in string recordID,
				in string remoteClinicServerName);
	};
};