package Server_Group.Replica_1.DSMS_CORBA;


/**
* DSMS_CORBA/DSMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Distributed_Staff_Management_System.idl
* Wednesday, July 27, 2016 5:40:24 PM EDT
*/

public interface DSMS extends DSMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMS
