package Server_Group.Replica_1.DSMS_CORBA;

/**
* DSMS_CORBA/DSMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Distributed_Staff_Management_System.idl
* Wednesday, July 27, 2016 5:40:24 PM EDT
*/

public final class DSMSHolder implements org.omg.CORBA.portable.Streamable
{
  public Server_Group.Replica_1.DSMS_CORBA.DSMS value = null;

  public DSMSHolder ()
  {
  }

  public DSMSHolder (Server_Group.Replica_1.DSMS_CORBA.DSMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Server_Group.Replica_1.DSMS_CORBA.DSMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
	  Server_Group.Replica_1.DSMS_CORBA.DSMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Server_Group.Replica_1.DSMS_CORBA.DSMSHelper.type ();
  }

}
